### PR TITLE
Catch exceptions on instrumentation error

### PR DESCRIPTION
**Pull request by floyd-fuh**
As discussed in #2 catch exceptions and warn user instead of failing to instrument

### CODE REVIEW

**Comment by floyd-fuh** [comment]
I've just added a pretty important feature: Security policy. It's actually really really nice, because it allows us to find several security issues such as Server Side Request Forgery (SSRF) or External Entity Injecting (XXE) by restricting what the Java process is allowed to access on the filesystem and network. It's like address sanitizer (ASAN) but for Java and not for memory corruptions but file and network access.

I added an example for the common-imaging. While I don't expect any issues from common-imaging, there might be image libraries parsing XMP metadata, leading to XXE. This would allow to detect such things.

**Comment by rodykersten** [comment]
Hi Floyd,

Thanks for your pull request. I've thought about the change a bit more, and decided not to incorporate it. In particular, catching the ClassNotFoundException where you suggest will not work, because when we then try to add the class to the output with loadAndWriteResource(), it will still not be found, leading to broken output. I'd rather have the instrumentor fail than produce broken output. Similarly, when a RuntimeException is thrown, other than the JSR/RET one, it is something we don't have an explanation for. I have not seen something like that before, so I'm not sure when that could occur. But I'm going to keep stopping instrumentation on unexpected events.

The security policy idea is very interesting! Did you find anything interesting using that approach?

Rody

**Comment by floyd-fuh** [comment]
Hi Rody,

Uhm, actually catching the ClassNotFoundException works very well and I've instrumented jars successfully. Let's say we find A.class and we want to instrument it. I guess the ClassNotFoundException is then rather thrown when an import can not be found, so when A.class imports com.class.that.does.not.exist. It doesn't mean A.class file is not there. In this case I still think it is the sane choice to use A.class as-is. Or maybe I'm just plain wrong.

Maybe download a wide variety of .jar files and try to instrument them with Kelinci, then you might see the issues.

No, so far I havent' found anything with the security policy, but I think it is kind of best practice to maximize instrumentation of a program and catch more error cases. Especially when it comes for free (security policy is basically for free whereas ASAN usually introduces an overhead).

**Comment by rodykersten** [comment]
In the case of a JAR it will work, because we start by making a copy of the JAR, then overwrite instrumented classes. In case of a directory of classes, it will break. I'll either add a special case for jars, or do the same for directories (start with a copy).

**Comment by floyd-fuh** [comment]
Ok, so if I understand you correctly you are saying catching ClassNotFoundException works fine as long as the Instrumentor is invoked for a .jar file? But not if the Instrumentor is invoked on a .class file directly? So basically as long as I'm only instrumenting jar files I should be fine?

**Comment by rodykersten** [comment]
Yes, if you're instrumenting jars you should be fine. If you're instrumenting a directory of class files, some classes may go missing.

**Pull request closed without merging**
